ALTER TABLE "SSHRemote"
ADD COLUMN "pricePerHour" DOUBLE PRECISION,
ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'USD',
ADD COLUMN "usageStartedAt" TIMESTAMP(3),
ADD COLUMN "usageEndedAt" TIMESTAMP(3),
ADD COLUMN "connectedAt" TIMESTAMP(3);
