import type { Metadata } from "next";

import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";

import { Aldrich } from "next/font/google";

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";
import { SiteHeader } from "@/components/dashboard/ui/side-headr";

const aldrich = Aldrich({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-aldrich",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className={`${aldrich.className} dark h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <TooltipProvider delayDuration={0}>
          
            <SidebarProvider
              style={
                {
                  "--sidebar-width": "calc(var(--spacing) * 72)",
                  "--header-height": "calc(var(--spacing) * 12)",
                } as React.CSSProperties
              }
            >
              <AppSidebar variant="inset" />
              <SidebarInset>
                <SiteHeader />
                {children}
              </SidebarInset>
            </SidebarProvider>
          
        </TooltipProvider>
      </body>
    </html>
  );
}
